naturalConcept/cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

naturalConcept/naturalConcept/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

naturalConcept/shop/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^create$', views.product_create, name='product_create'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/delete/$', views.product_delete, name='product_delete'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/update/$', views.product_update, name='product_update'),
]

naturalConcept/shop/views.py
from django.shortcuts import render, get_object_or_404
from django.core.files.storage import FileSystemStorage
from django.contrib import messages
from django.shortcuts import redirect
from django.core.urlresolvers import reverse_lazy
from cart.forms import CartAddProductForm
from facade import Fachada
from .forms import ProductUpdateForm
from .models import Category, Product

def product_list(request, category_slug=None):
    fachada = Fachada()
    category = None
    categories = Category.objects.all()
    # metodo listar da fachada
    products = fachada.listar(available=True)

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/list.html', {'category': category,
                                                      'categories': categories,
                                                      'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'shop/product/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form})

def product_delete(request, id, slug):
    fachada = Fachada()
    try:
        fachada.remover_produto(id=id, slug=slug)
    except Exception as e:
        print(e)
        messages.warning(request, "Produto não existe mais")
        return redirect(reverse_lazy('shop:product_list'))

    messages.success(request, "Produto removido com sucesso!")
    return redirect(reverse_lazy('shop:product_list'))

def product_update(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug)
    if request.method == 'POST':
        form = ProductUpdateForm(request.POST, request.FILES)
        if form.is_valid():
            fachada = Fachada()
            cd = form.cleaned_data
            if cd['image']:
                fs = FileSystemStorage()
                fs.save(cd['image'].name, cd['image'])

            if not cd['image']:
                del cd['image']

            try:
                fachada.atualizar_produto(idProduto=id, **cd)
            except Exception as e:
                messages.warning(request, str(e))
                return redirect(reverse_lazy('shop:product_list'))
            messages.success(request, "Produto atualizado com sucesso!")
            return redirect(reverse_lazy('shop:product_list'))
        else:
            form = ProductUpdateForm()
            return render(request, 'shop/product/update.html', {'form': form})
    form = ProductUpdateForm(instance=product)
    return render(request, 'shop/product/update.html', {'form': form})

def product_create(request):
    if request.method == 'POST':
        form = ProductUpdateForm(request.POST, request.FILES)
        if form.is_valid():
            fachada = Fachada()
            cd = form.cleaned_data
            if cd['image']:
                fs = FileSystemStorage()
                fs.save(cd['image'].name, cd['image'])

            try:
                fachada.adicionar_produto(**cd)
            except Exception as e:
                messages.warning(request, str(e))
                return redirect(reverse_lazy('shop:product_list'))
            messages.success(request, "Produto adicionado com sucesso!")
            return redirect(reverse_lazy('shop:product_list'))
        else:
            form = ProductUpdateForm()
            return render(request, 'shop/product/create.html', {'form': form})
    form = ProductUpdateForm()
    return render(request, 'shop/product/create.html', {'form': form})

naturalConcept/shop/templates/shop/product/create.html
{% extends "shop/base.html" %}

{% block title %}
    Adicionar
{% endblock %}

{% block content %}
    <h1>Adicionar</h1>

    <form method="post" enctype="multipart/form-data" class="order-form">
        {% csrf_token %}
        {{ form.as_p }}
        <p><input type="submit" value="Adicionar"></p>
    </form>
{% endblock %}

naturalConcept/shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    {{ product.name }}
{% endblock %}

{% block content %}
    <div class="product-detail">
        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        <h1>{{ product.name }}</h1>
        <h2><a href="{% url 'shop:product_delete' product.id product.slug %}">Apagar</a></h2>
        <h2><a href="{% url 'shop:product_update' product.id product.slug %}">Atualizar</a></h2>
        <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
        <p class="price">R${{ product.price }}</p>
        <form action="{% url "cart:cart_add" product.id %}" method="post">
            {{ cart_product_form }}
            {% csrf_token %}
            <input type="submit" value="Adicionar ao carrinho">
        </form>
        {{ product.description|linebreaks }}
    </div>
{% endblock %}

        
        
        

naturalConcept/shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    {% if category %}{{ category.name }}{% else %}Produtos{% endif %}
{% endblock %}

{% block content %}
    <div id="sidebar">
        <h3>Categorias</h3>
        <ul>
            <li {% if not category %}class="selected"{% endif %}>
                <a href="{% url "shop:product_list" %}">Todos</a>
            </li>
            {% for c in categories %}
                <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                    <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                </li>
            {% endfor %}

        </ul>
    </div>
    <div id="main" class="product-list">
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <h1>{% if category %}{{ category.name }}{% else %}Produtos{% endif %}</h1>
        {% for product in products %}
            <div class="item">
                <a href="{{ product.get_absolute_url }}">
                    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
                </a>
                <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
                R${{ product.price }}
            </div>
        {% endfor %}
        <div class="item">
            <a href="{% url 'shop:product_create' %}">
                <img src="{% static "img/no_image.png" %}">
            </a>
            <a href="{% url 'shop:product_create' %}">Adicionar produto</a><br>
        </div>
    </div>
{% endblock %}

naturalConcept/shop/templates/shop/product/update.html
{% extends "shop/base.html" %}

{% block title %}
    Atualizar
{% endblock %}

{% block content %}
    <h1>Atualizar</h1>

    <form action="." method="post" enctype="multipart/form-data" class="order-form">
        {% csrf_token %}
        {{ form.as_p }}
        <p><input type="submit" value="Atualizar"></p>
    </form>
{% endblock %}